/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE BATTERY_STATUS PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * Battery information. Updates GCS with flight controller battery status. Smart batteries also use this message, but may additionally send SMART_BATTERY_INFO.
 */
public class msg_battery_status extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_BATTERY_STATUS = 147;
    public static final int MAVLINK_MSG_LENGTH = 36;
    private static final long serialVersionUID = MAVLINK_MSG_ID_BATTERY_STATUS;

      
    /**
     * Consumed charge, -1: autopilot does not provide consumption estimate
     */
    public int current_consumed;
      
    /**
     * Consumed energy, -1: autopilot does not provide energy consumption estimate
     */
    public int energy_consumed;
      
    /**
     * Temperature of the battery. INT16_MAX for unknown temperature.
     */
    public short temperature;
      
    /**
     * Battery voltage of cells 1 to 10 (see voltages_ext for cells 11-14). Cells in this field above the valid cell count for this battery should have the UINT16_MAX value. If individual cell voltages are unknown or not measured for this battery, then the overall battery voltage should be filled in cell 0, with all others set to UINT16_MAX. If the voltage of the battery is greater than (UINT16_MAX - 1), then cell 0 should be set to (UINT16_MAX - 1), and cell 1 to the remaining voltage. This can be extended to multiple cells if the total voltage is greater than 2 * (UINT16_MAX - 1).
     */
    public int voltages[] = new int[10];
      
    /**
     * Battery current, -1: autopilot does not measure the current
     */
    public short current_battery;
      
    /**
     * Battery ID
     */
    public short id;
      
    /**
     * Function of the battery
     */
    public short battery_function;
      
    /**
     * Type (chemistry) of the battery
     */
    public short type;
      
    /**
     * Remaining battery energy. Values: [0-100], -1: autopilot does not estimate the remaining battery.
     */
    public byte battery_remaining;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_BATTERY_STATUS;
        
        packet.payload.putInt(current_consumed);
        packet.payload.putInt(energy_consumed);
        packet.payload.putShort(temperature);
        
        for (int i = 0; i < voltages.length; i++) {
            packet.payload.putUnsignedShort(voltages[i]);
        }
                    
        packet.payload.putShort(current_battery);
        packet.payload.putUnsignedByte(id);
        packet.payload.putUnsignedByte(battery_function);
        packet.payload.putUnsignedByte(type);
        packet.payload.putByte(battery_remaining);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a battery_status message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.current_consumed = payload.getInt();
        this.energy_consumed = payload.getInt();
        this.temperature = payload.getShort();
         
        for (int i = 0; i < this.voltages.length; i++) {
            this.voltages[i] = payload.getUnsignedShort();
        }
                
        this.current_battery = payload.getShort();
        this.id = payload.getUnsignedByte();
        this.battery_function = payload.getUnsignedByte();
        this.type = payload.getUnsignedByte();
        this.battery_remaining = payload.getByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_battery_status() {
        this.msgid = MAVLINK_MSG_ID_BATTERY_STATUS;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_battery_status( int current_consumed, int energy_consumed, short temperature, int[] voltages, short current_battery, short id, short battery_function, short type, byte battery_remaining) {
        this.msgid = MAVLINK_MSG_ID_BATTERY_STATUS;

        this.current_consumed = current_consumed;
        this.energy_consumed = energy_consumed;
        this.temperature = temperature;
        this.voltages = voltages;
        this.current_battery = current_battery;
        this.id = id;
        this.battery_function = battery_function;
        this.type = type;
        this.battery_remaining = battery_remaining;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_battery_status( int current_consumed, int energy_consumed, short temperature, int[] voltages, short current_battery, short id, short battery_function, short type, byte battery_remaining, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_BATTERY_STATUS;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.current_consumed = current_consumed;
        this.energy_consumed = energy_consumed;
        this.temperature = temperature;
        this.voltages = voltages;
        this.current_battery = current_battery;
        this.id = id;
        this.battery_function = battery_function;
        this.type = type;
        this.battery_remaining = battery_remaining;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_battery_status(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_BATTERY_STATUS;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_BATTERY_STATUS - sysid:"+sysid+" compid:"+compid+" current_consumed:"+current_consumed+" energy_consumed:"+energy_consumed+" temperature:"+temperature+" voltages:"+voltages+" current_battery:"+current_battery+" id:"+id+" battery_function:"+battery_function+" type:"+type+" battery_remaining:"+battery_remaining+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_BATTERY_STATUS";
    }
}
        